<?php /*
<?php $imgSize = Mage::helper('kalolia/data')->getImgSize('L'); ?>
<?php
	$_helper = $this->helper('catalog/output');
	$_product = $this->getData("product"); ?>
<div class="content-cfbox">
	<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgSize[0]/1.8, $imgSize[1]/1.8); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
	
	<div class="cf-producinfo">
		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgSize[0], $imgSize[1]); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
		<h3 class="product-name">
			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
		</h3>
        <?php if ($_product->getShortDescription()):?>
             <div class="short-description">
                 <?php echo substr($_product->getShortDescription(),0, 70).'...' ; ?>
             </div>
        <?php endif;?>
	</div>
 	<div class="cf-moreinfo">
		<?php if( $this->getReviewsSummaryHtml($_product, 'short')){ ?>
		<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
		<?php } ?>
		<div class="price-container">
			<?php echo $this->getPriceHtml($_product, true) ?>
		</div>
	</div>
	
</div>	

*/ ?>