<?php

 $posts = $this->getPosts();
// echo "<pre>";
//var_dump($posts);exit;
 // echo "</pre>"; 
 ?>
<?php
	if($posts) :
	$blockId ='sns_latestblog_'.rand().time();
?>
<div class="block block-latest-list" id="<?php echo $blockId; ?>">
	<div class="block-title">
		<span><?php echo $this->__('LATEST BLOGS');?></span>
		
	</div>
	<div class="block-content">
	    <div class="list-blog-item">
	    <?php $j=0; foreach ($posts as $post): ?>
	        <?php
			
		        $j++;
		        if($j>5) break;
			?>
	        <div class="item-post<?php echo ($j==3)?' last':'';?> clearfix">
	            <?php
					
		            $str = $post->getPostContent();
		            $str = preg_replace ( "/\<img[^\>]*>/", '', $post->getPostContent());
	            ?>
	            <a class="post-img" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" >
	                <?php $imgUrl = Mage::helper('kalolia/data')->getImgUrl($post->getPostContent()); ?>
	                <img <?php echo $imgUrl; ?> alt="<?php echo $post->getTitle(); ?>" />
	            </a>
	            <div class="post-title">
	                <a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a>
					<div class="date">
					<?php 
					$_ct= new Zend_Date($post->getCreatedTime()); 
					echo $_ct->toString('MMM').','; 
					echo $_ct->toString('YYYY').','; 
					echo $_ct->toString('d'); 
					?>
					</div>
	            </div>	 
	        </div>
	    <?php endforeach; ?>
	    </div>
	</div>
</div>
<?php endif; ?>