<?php

 $posts = $this->getPosts();
// echo "<pre>";
//var_dump($posts);exit;
 // echo "</pre>"; 
 ?>
<?php
	if($posts) :
	$blockId ='sns_latestblog_'.rand().time();
?>
<div class="block block-latestblog" id="<?php echo $blockId; ?>">
<div class="header-title">
	<div class="block-title">
		<span><span><?php echo $this->__('LATEST BLOGS');?></span></span>
	</div>
</div>
	<div class="block-content">
	    <div class="list-blog">
	    <?php $j=0; foreach ($posts as $post): ?>
	        <?php
			
		        $j++;
		        if($j>7) break;
			?>
	        <div class="item-post<?php echo ($j==3)?' last':'';?> clearfix">
	            <?php
					
		            $str = $post->getPostContent();
		            $str = preg_replace ( "/\<img[^\>]*>/", '', $post->getPostContent());
	            ?>
	            <a class="post-img" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" >
	                <?php $imgUrl = Mage::helper('kalolia/data')->getImgUrl($post->getPostContent()); ?>
					<i class="fa fa-link"></i>
	                <img  <?php echo $imgUrl; ?> alt="<?php echo $post->getTitle(); ?>" /> 
	            </a>
				<div class="date">
					<?php $_ct= new Zend_Date($post->getCreatedTime()); ?>
					<span class="d-month"><?php echo $_ct->toString('MMM'); ?> </span>
					<span class="d-day"><?php echo $_ct->toString('d');  ?></span>
				</div>
	            <div class="post-title">
	                <a href="<?php echo $post->getAddress(); ?>" ><?php $title= $post->getTitle(); echo substr($title,0,25).'...';?></a>
	            </div>
	           
	            <div class="post-content">
	                <?php echo Mage::helper('core/string')->truncate($str, 70); ?>
	            </div>
	        </div>
	    <?php endforeach; ?>
	    </div>
	</div>
	<script>
		jQuery(document).ready(function($) {
			$(window).load(function(){
				$('#<?php echo $blockId; ?> .list-blog').owlCarousel({
					items:2,
					itemsCustom: [
						[0, 1],
						[480, 2],
						[768, 1],
						[992, 2]
					],
					pagination: true,
					itemsScaleUp : true,
					slideSpeed : 800,
					autoPlay: true,
					addClassActive: true,
					navigation: false,
					afterAction: function (e) {
					    if(this.$owlItems.length > this.options.items){
					        $('#<?php echo $blockId; ?> .navslider').show();
					    }else{
					        $('#<?php echo $blockId; ?> .navslider').hide();
					    }
					}
				});
				
			});
		});
	</script>
</div>
<?php endif; ?>