<?php
/*------------------------------------------------------------------------
 # SNS Slider - Version 2.0
 * Copyright (C) 2013 The SNS Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: SNS Theme
 * Websites: http://www.snstheme.com
-------------------------------------------------------------------------*/
$themeConfig =   Mage::helper('twen/data')->get();
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}
$uniqued = rand().time();

$imgSize = Mage::helper('twen/data')->getImgSize('L');
$imgWidth = 145;
$imgHeight = 155;
?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="sns_lider<?php echo $uniqued; ?>" class="product-bottom block sns-slider<?php echo($this->effects)?' effect-'.$this->effects:'';?>">
	<div class="slider-inner">
		    	<div class="block-title">
		    		<?php if($this->title!="") : ?>
		    		<strong><?php echo $this->title;?></strong>
					<?php endif; ?>
		            <?php if($this->navigation): ?>
						<div class="navslider">
							<a class="prev" href="#"><i class="fa fa-angle-left"></i></a>
							<a class="next" href="#"><i class="fa fa-angle-right"></i></a>
						</div>
		            <?php endif; ?>
		    	</div>
		    	
	    		<?php if($this->pretext): ?>
	    			<p><?php echo $this->pretext; ?></p>
	    		<?php endif; ?>
	    		
			    <div class="container-slider">
				    <div class="products-grid">
				    <?php foreach($_productCollection as $_product) : ?>
				        <?php
				        $now = date("Y-m-d");
				        $newsFrom= substr($_product->getData('news_from_date'),0,10);
				        $newsTo=  substr($_product->getData('news_to_date'),0,10);
				        $price = $_product->getPrice();
				        $finalPrice = $_product->getFinalPrice();
				        $class = '';
				        if($now>=$newsFrom && $now<=$newsTo) $class .= ' have-iconew';
				        if( isset($price) && isset($finalPrice) && $finalPrice < $price) $class .= ' have-icosale';
						if($i%2 == 0) {
							echo '<div class="row-item">';
						}
				        ?>
				        <div class="item <?php if($i%2==0) echo "first"?>">
							<div class="item-inner clearfix">
			            		<div class="badges">
				                    <?php
				                    if ($now>=$newsFrom && $now<=$newsTo && $themeConfig['general_useTagNew']==1)
				                        echo "<span class='ico-product ico-new'>New</span>";
				                    if (isset($price) && isset($finalPrice) && $finalPrice < $price && $themeConfig['general_useTagNew']==1)
				                        echo "<span class='ico-product ico-sale'>-".floor(100-($finalPrice/$price)*100)." %</span>";
				                    ?>
			                    </div>
			                    		
			                    		
			                    		
				                <div class="item-img<?php echo $class; ?>">
			                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
			                        	<span class="image-main">
			                            	<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth, $imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
			                        	</span>
			                        </a>
									
				                </div>

			                    <div class="item-info">
			                        <div class="info-inner">
			                            <?php if( $this->product_rating_summary == 1 ) : ?>
			                            <div class="rating">
			                            <?php  // echo $this->getReviewsSummaryHtml($_product, false, true)?>
			                            </div>
			                            <?php endif; ?>
			                            
				                        <?php if( $this->product_title_disp == 1 ) : ?>
				                        <div class="item-title">
				                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
				                            <?php
				                                if ( $this->product_title_max_length > 0){
				                                    $_productNameTruncated = Mage::helper('core/string')->truncate($_productNameStripped, $this->product_title_max_length);
				                                }
				                            ?>
				                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo isset($_productNameTruncated) ? $_productNameTruncated : $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a>
				                        </div>
				                        <?php endif; ?>
				                         <?php if( $this->product_price_disp ) : ?>
				                            <div class="item-price">
				                                <?php echo $this->getPriceHtml($_product, false, $uniqued) ?>
				                            </div>
				                            <?php endif; ?>		
			                        </div>
			                    </div>
							</div>
				        </div>
						<?php
							$i++;
							if($i%2 == 0 || $i == $_productCollection->count()) {
								echo '</div>'; // endrow
							}
						?>
				    <?php endforeach; ?>
				    </div>
				    	
			    <?php if($this->posttext): ?>
			    <div class="posttext"><div><?php var_dump($this->posttext); exit; ?></div></div>
			    <?php endif; ?>

		</div>
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        $('#sns_lider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
			items:3,
            itemsCustom: [ 
				[0, 1],
				[480, 2],
				[640, 3]
            	
				
        	],
            <?php if($this->auto){ ?>
            autoPlay: true,
            stopOnHover: true,
            <?php } ?>
            <?php if($this->duration){ ?>
            slideSpeed: <?php echo $this->duration; ?>,
            <?php } ?>
            pagination: false,
            slideSpeed : 800,
            addClassActive: true,
			afterAction: function (e) {
			    if(this.$owlItems.length > this.options.items){
			        $('#sns_lider<?php echo $uniqued; ?> .navslider').show();
			    }else{
			        $('#sns_lider<?php echo $uniqued; ?> .navslider').hide();
			    }
			}
            //scrollPerPage: true,
        });
		$('#sns_lider<?php echo $uniqued; ?> .navslider .prev').on('click', function(e){
			e.preventDefault();
			$('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('owl.prev');
		});
		$('#sns_lider<?php echo $uniqued; ?> .navslider .next').on('click', function(e){
			e.preventDefault();
			$('#sns_lider<?php echo $uniqued; ?> div.products-grid').trigger('owl.next');
		});
    });
//]]>
</script>
<?php endif; ?>