<?php
	$themeCfg = Mage::helper('kalolia/data');
	$enabled = $themeCfg->getField('ourpartners_enabled');
	if($enabled == 1) :
		$partners = $themeCfg->getField('ourpartners_partners');
		$array_partners = unserialize($partners);
		$id = 1;
		$collect_partners = array();
		foreach($array_partners as $key=>$partner){
			$partner['id'] = $id;
			$partner['image'] = Mage::helper('cms')->getBlockTemplateProcessor()->filter($partner['image']);
			if (preg_match('/^wysiwyg/i', $partner['image'])) {
				$partner['image'] = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$partner['image'];
			}
			$partner['link'] = Mage::helper('cms')->getBlockTemplateProcessor()->filter($partner['link']);
			$haveHttp =  strpos(trim($partner['link']), "http://"); 
			if(!$haveHttp && ($haveHttp!==0)){
				//$partner['link'] = "http://" . trim($partner['link']);  
			}else {
				//$partner['link'] = trim($partner['link']);
			}
			
			
			$partner['title'] = $partner['title'];
			$collect_partners[] = $partner;
			$id++;
		}
if($collect_partners) :
	$blockId ='sns_partner_'.rand().time();
	$count_item = count($collect_partners);
?>
<div id="sns_partners">
		<div class="sns_partner" id="<?php echo $blockId; ?>">
			<div class="block_head">
				<div class="block-title"><span><span><?php echo $themeCfg->getField('ourpartners_title'); ?></span></span></div>
				
			</div>
			<div class="partners_slider slider-wrap">
				<div class="partners_slider_in">
					<div class="our_partners" style="display: none;">
						<?php foreach($collect_partners as $partner) : ?>
						<?php 
						
						if($i%2 == 0) {
							echo '<div class="row-item">';
							}
						?>
							<div class="wrap">
								<div class="wrap_in">
									<a target="_blank" href="<?php echo $partner['link']; ?>">
										<img alt="" src="<?php echo $partner['image']; ?>" />
									</a>
								</div>
							</div>
						<?php
							$i++;
							if($i%2 == 0 || $i== $count_item) {
								echo '</div>'; // endrow
							}
						?>
						<?php endforeach; ?>
					</div>
				</div>
			</div>
			<script>
				jQuery(document).ready(function($) {
					$(window).load(function(){
						$('#<?php echo $blockId; ?> .our_partners').owlCarousel({
							items:3,
							itemsCustom: [
								[0, 2],
								[480, 3],
								[768, 2],
								[992, 3]
							],
							pagination: true,
							itemsScaleUp : true,
							slideSpeed : 800,
							autoPlay: true,
							addClassActive: true,
							navigation: false,
							afterAction: function (e) {
							    if(this.$owlItems.length > this.options.items){
							        $('#<?php echo $blockId; ?> .navslider').show();
							    }else{
							        $('#<?php echo $blockId; ?> .navslider').hide();
							    }
							}
						});
					});
					/*
					$('#<?php echo $blockId; ?> .navslider .prev').on('click', function(e){
						e.preventDefault();
						$('#<?php echo $blockId; ?> .our_partners').trigger('owl.prev');
					});
					$('#<?php echo $blockId; ?> .navslider .next').on('click', function(e){
						e.preventDefault();
						$('#<?php echo $blockId; ?> .our_partners').trigger('owl.next');
					});
					*/
				});
			</script>
		</div>
</div>
<?php endif; ?>
<?php endif; ?>